src/jquery.contextMenu.js

$currentTrigger was being used when it could be null, added check for truthiness (should guard against null use) before use in the 'key' handler.

Issue with using $currentTrigger when it is null

---

src/jquery.contextMenu.js

Fixes issue #197 
Does make IE9 behave a little weird see #80

Fix for growing menu width for issue #197

---

demo/html5-import.html
src/jquery.contextMenu.js

I added this line at the code so we can create icons in html5 structure.
Would appretiate the merge!!
This solves the issue #240

Adding icon feature to html5 context menu

---

bower.json
contextMenu.jquery.json
package.json

Tested different jquery versions. Seems 1.8.2 and up works, so minimum requirements upped to 1.8.2
Fixes #261

jQuery works from 1.8.2 and up.

---

.travis.yml
package.json

Update some dependencies. Updating travis to the new infrastructure breaks testing unfortunately.

Feature dependencies update

---

docs.html
src/jquery.contextMenu.js

Fix copy/paste error in documentation
Added visible option to item
Improvements: if all options are hidden - don't show menu

Added visible option to item

---

src/jquery.contextMenu.js

Change text to HTML as suggested by @UziTech in PR #256

change .text to .html when adding item.name to the item fixes #252

---

src/jquery.contextMenu.css
src/jquery.contextMenu.js

Fixed pull request Kccarter76 

---

src/jquery.contextMenu.css
src/jquery.contextMenu.js

I have added the ability for a left click on demand menu and I have reworked the sub menu presentation to be touch friendly. before access to a sub menu via a touch interface was not possible.

My updates to context menu

---

src/jquery.contextMenu.js

Allows dynamic icons by supporting function for icon option (in addition to the current "string" option):
someKey: { name: "some name", icon: function (trigger, key,  item) { return getIconFromSomewhere(key); } }

Add feature: dynamic icons

---

src/jquery.contextMenu.js
test/unit/test-events.js

The context menu was not opening when x or y were 0.

open contextMenu at 0,0

---

src/jquery.contextMenu.js

There is already similar code for offset.top. offset.left should also need it.

Do not place menu outside of client area

---

src/jquery.contextMenu.js

This pull request referrers to this issue  #309 
Not sure if this was a error or if it was intended to work like it did before. But i have changed the code so it works at the docs says it should work.

Fixed a problem there was when using a function for icons

---

src/sass/jquery.contextMenu.scss

Fixed a problem where submenus resized wrong

---

src/jquery.contextMenu.js

This is a update on pull request #251 
I just fixed the merge conflict. Now it can be merged and this should also fix issue #293

Fixed a problem where the contextmenu would open another menu

---

src/jquery.contextMenu.js

I made this change so that is it possible to click the span with the text also to trigger the change event on inputs. Also this will make radio and check boxes be on the same line as the text instead of using two lines for those.

Changed the defuat types. Now the span is inside the label

---

src/jquery.contextMenu.js

Add check that root.$layer exists, to prevent calling hide() on an defined object.

---

.travis.yml
README.md

Use travis container based infrastructure instead of legacy one.

Use travis container

---

documentation/docs/customize.md

I found this while trying to add some custom icons.

Improve docs on icon additions

---

documentation/docs.md
src/jquery.contextMenu.js

Adding ability to click on submenus. New option parameter selectableSubMenu, false by default

New Feature, selectable Sub Menus

---

src/jquery.contextMenu.js

Just check if the given selected Value is a boolean, if it is a int cast it to a string.

check if given selected value is a 0, if it is a zero so return it as

---

CHANGELOG.md
src/jquery.contextMenu.js

Be a little more conservative in the zIndex check

Possible fix for issue #506

---

src/jquery.contextMenu.js

Fix #211 include triggering event in menu callback

---

src/jquery.contextMenu.js

I added "activated" events so user can run desire function after contextMenu showed in page.
And a handler for over boundary problem with small resolution or even context menu with a lot of items.
In over boundary situation context menu will get scroll.

Adding "activated" event and handling over boundary problem.

---

documentation/demo/callback.md

Callback argument did not match the variable in the console.log

Fix typo in documentation which breaks the callback demo.

---

src/jquery.contextMenu.js

I fixed that the context menu is displayed inside the screen when scrolling down the page.

A context menu appears outside the screen Under certain conditions

---

src/jquery.contextMenu.js

see [#721](https://github.com/swisnl/jQuery-contextMenu/issues/721)

fix when add layer cause page forced reflow
