swisnl/jQuery-contextMenu

src/jquery.contextMenu.js

Allows the browser right-click to work if the user has not used the right mouse button as a trigger.

Fix for Issue #138

---

src/jquery.contextMenu.js

This fix is for #166 
`$.support.fixedPosition` is also `true`  in IE8 despite of it's support of position fix.
So I changed if-statement for judging IE6. 
(`$.browser` is removed from jQuery 1.9 above. I think it's most simple sentence to judge IE6)

Fix  issue #166

---

src/jquery.contextMenu.js

When i will show the contextMenu that height+position of click is greater than window height a part of the contextmenu is hidden because it will show the contextMenu above the position of click.
Example

contextMenu always visible in window

---

src/jquery.contextMenu.js

(console.error || console.log)("No items specified to show in contextMenu");
Creates an error in Chrome : Uncaught TypeError: Illegal invocation       jquery.contextMenu.js:250

Update jquery.contextMenu.js for Uncaught TypeError: Illegal invocation in Chrome

---

src/jquery.contextMenu.js

The string passed to the menu items is eventually "eval"ed by jQuery, so using .html() allows XSS to get through and get executed by the browser.

Changed .html() to .text()

---

src/jquery.contextMenu.js

Fixed an uncaught error in contextMenu when data('contextMenu') is undefined (for example when .contextMenu() is used on an element without an initialized contextMenu). 
Also added a "first()" method call to better match the documentation which says that .contextMenu("hide") should "hide the contextMenu of the first element of the selector".

Fixed an uncaught error in contextMenu()

---

README.md
demo.html
demo/accesskeys.html
demo/accesskeys_test.html
demo/callback.html
demo/callback_test.html
demo/disabled-menu.html
demo/dynamic-create.html
demo/dynamic.html
demo/menu-title.html
demo/on-dom-element.html
demo/trigger-custom.html
demo/trigger-hover-autohide.html
demo/trigger-hover.html
demo/trigger-left-click.html
src/jquery.contextMenu.js

Item icon can now be a callback to dynamically decide on icon class.
References:
Issue #158 
Issue #129 
Issue #151 
Issue #249

Feature icon callback option

---

package.json

I'm having some issues of duplicated jQuery instances when using jQuery contextMenu with npm 3.x. This works great when jQuery is declared as a peer dependency (and this is the recommended declaration of dependencies for plugins).

Update package.json to set jquery dep as peer dependency

---

src/jquery.contextMenu.js

https://github.com/swisnl/jQuery-contextMenu/commit/83e37fbd3c6b0ca113597c01f03f62757cf86ecb changes .text() back to .html(), and it introduces the XSS risk again, that was once fixed by https://github.com/swisnl/jQuery-contextMenu/commit/f3137f21e17d3f91dad6f913eb3a0e93ada35b8a
accesskey's span element should be inserted separately from before/after text, to avoid parsing HTML there.

Do not use .html() to markup accesskey

---

src/jquery.contextMenu.js

With this fix you are now able to make a seperator two ways:
1. Old way
"sep1": "----------"
2. like a item where you set the type
"sep2": { "type": "cm_seperator" }
the possible outcome of this is that you can now use the visible function on a seperator that i missed was possible since i make alot of dynamic contextmenus and i did not have to hide the span if i gave the seperator a name.

Fixed a swith to use the correct type for seperators

---

src/jquery.contextMenu.js
src/sass/jquery.contextMenu.scss

Using the css code i made before was wrong. I found out that if you changed the $menu.width() to $menu.outerWidth() it would get the correct size.
This pull request can close the issue #308 problem solved and fixed.

Properly fixed the problem with submenus size wrongly

---

src/jquery.contextMenu.js

When a selector has been assigned to the appendTo option, the context menu wasn't (always?) positioned at the cursor position.
This fix solves the problem.

Positioning of contextmenu when using appendTo

---

src/jquery.contextMenu.js

I had a problem where e.offsetX and e.offsetY is undefined. This was mainly when i used the open function like the example below.
`$(selector).contextMenu({ x: ShowX, y: ShowY });`
So i have made a check if they are undefined and if they are pageX and pageY are used instead.

Fixed a problem when using the open function

---

documentation/docs.md

➊ Unlike the jQuery ID selector, the correct syntax for `document.getElementById()` does not use `#` in its argument string.
➋ In the value section of `trigger`, `appendTo `was mistakenly used in place.
➌ In the 2nd example for `trigger`, the first line stores the `context-menus-container` DOM element inside a variable, but it serves no purpose later on.

Correct typos / mistakes in the main documentation page

---

gulpfile.js

#380 On windows at least, the woff2 font file is not created, and without it, icons are not displayed.

force font woff2 creation

---

bower.json

`version` option is _deprecated_ and is ignored by **Bower**, as mentioned in its [specification](https://github.com/bower/spec/blob/master/json.md#version).

Remove deprecated option in 'bower.json'.

---

src/jquery.contextMenu.js

Using jQuery contextMenu with d3 tree (http://bl.ocks.org/mbostock/4339083) object creates a problem with positioning the menu in wrong place.
ContextMenu in opening time checks "offsetX" attribute of event and in case if exists, it does some calculation to position the menu. But in combination with d3 tree, this value will be calculated wrong and menu will be positioned in far right side of page. I have seen in absence of "offsetX" attribute, "pageX" is used. I could fix this issue with replacing the whole condition block with just else part. 
Is there any reason for using offsetX when pageX exists all the time?

Bugfix: fixed positioning context menu when used with d3 tree

---

documentation/docs/items.md
src/jquery.contextMenu.js

After upgrading to 2.x, one thing that has changed since 1.8.1 is the ability to put styled HTML into the names of entries. It is useful to allow for the use of this, even though it could have a potential security risk for dynamically named items.

adding option for menu item name to use html() instead of text()

---

documentation/docs/items.md

- Option name (`visible`)
- Options type (`disabled`, `visible`)

Fix typo in items documentation

---

documentation/docs.md

https://swisnl.github.io/jQuery-contextMenu/docs.html#events
Argument name in events examples.

Typo in documentation

---

src/jquery.contextMenu.js

Ability to create a separator item by using additional alias:
```js
items: {
'sep0': '----', // Any string
'sep1': { type: 'cm_seperator' }, // 1
'sep2': { type: 'cm_separator' } // 2
}
```
Closes #411

Alias for 'cm_seperator' type: 'cm_separator'.

---

documentation/docs.md

`show` is used twice, I _assume_ from the context that the second `show` should actually be a `hide`.

Change second 'show' to 'hide' in events docs

---

src/jquery.contextMenu.js

This is a pull-request for issue #352 which I've reported eariler. I used to get quite a lot of Javascript errors of this kind reported on play.freeciv.org by Trackjs (error reporting tool).
I have been using this change in production on play.freeciv.org for about one week, and it has resolved all these javascript errors from being reported any more.

Add checks for null before using opt.$menu and root.$menu.

---

src/jquery.contextMenu.js

- changed `<input>` to `<input />`
- removed second value attribute value=""; xhtml does not allow duplicated attributes (was there a reason for the second one?)
- added missing end tag `</select>` to `<select>` tag; also required by html

make <input< and <select> tags xhtml compatible

---

src/jquery.contextMenu.js

Add check for if opt.$menu is null when handling ESC key callback.
This bug can be reproduced in the following way:
1. Go to Freeciv-web on https://play.freeciv.org and start a game.
2. Right-clicking on a unit, then the context menu is shown.
3. Press the ESC key.
4. Then a Javascript error occurs in the JavaScript console.

Add check for if opt.$menu is null when handling ESC key callback.

---

src/jquery.contextMenu.js

Hi,
Issue: #429
With this feature it is possible to load sub-menu items AFTER the context menu has been opened. By providing a [Jquery promise](http://api.jquery.com/deferred.promise/) for the "items". After the promise will be resolved or rejected the items will be shown in the context menu.
Example usage:
```javascript
var errorItems = { "errorItem": { name: "Could not load items" },};//example usage if you want to reject promise
var loadItems = function () {//example method that will eventually do an async call
var dfd = jQuery.Deferred();
setTimeout(function () {
dfd.resolve(subItems);
}, 1000);
//setTimeout(function () {
//    dfd.reject(errorItems);
//}, 1000); //could be used to reject items, providing the same format list.
return dfd.promise();//return a jquery promise, see …
```

Context menu async loading sub-menu's

---

package.json

In order to use the scss files we need to include the src directory on install

Include src files on install

---

src/jquery.contextMenu.js

In my app, sometimes menu is empty (i.e. [o param is empty](https://github.com/swisnl/jQuery-contextMenu/blob/master/src/jquery.contextMenu.js#L1658)), i think this condition it will not be superfluous

Add check on destroy (Menu can be empty)

---

src/jquery.contextMenu.js

When we have the context menu open and the `context-menu-layer` is being shown, subsequent right clicks on contenteditable elements won't focus the cursor on them. This PR will check if the target element of a right click is a contenteditable element, and if so, use window.getSelection() to focus it.

add focus for contenteditable elements on `context-menu-layer` right click

---

src/jquery.contextMenu.js

The inline style causes a Content Security Policy violation if _style-src 'unsafe-inline'_ is not defined in the policy.
Moved the style data to the CSS function below, which is permitted when a strict CSP is configured.

moved in-line style for context-menu-layer

---

src/jquery.contextMenu.js

This prevents calling trigger() on an undefined object. Based on my testing opt.$menu != null should be used to check for undefined, since this fixes the actual error based on my testing.
This is related to my previous pull request here:
https://github.com/swisnl/jQuery-contextMenu/pull/462

Check for opt.$menu != null instead of opt.$menu !== null.

---

src/jquery.contextMenu.js

Fixes #454 - events not triggering when opening a contextMenu right after the other

events not triggering

---

src/jquery.contextMenu.js

As the title says...
I was surprised to discover that the default behaviour when clicking on the trigger element a second time is to reposition the menu. However I had set-up the trigger to respond to left clicks, so given that right clicks are the default trigger action reposition makes more sense. 
It still seemed like a good idea to have the option of hiding the menu on a second trigger though; I think this would be the expected behaviour in the case of left-clicks or touch-screen taps (hence my initial surprise ;)). Perhaps this could even be the default behaviour for left-click or touch-screen taps? For now this PR is only adding the option and setting it to false by default.

Add option to hide the menu on a second click/trigger of the trigger element

---

src/jquery.contextMenu.js

Quick implementation for #669 - adds a preShow - callback to the events. When the callback returns false, browsers native menu is shown.

Pre-Show callback to display native menu

---

documentation/docs/items.md

the documentation suggests there are 4 parameters passed to the function, but there are only 3 parameters. Removed the `rootMenu` parameter mentioned...

updated documentation for `callback`

---

src/sass/_variables.scss

Add `!default` after 
vars `$context-menu-icon-color` and `$context-menu-icon-color-hover`, so users of this module can supply their own values.

Allow overriding default icon colors

---

src/jquery.contextMenu.js

This adds in changes proposed by @lukefoley in issue #749, but uses $menu.outerHeight() instead of $menu.height() so that part of the menu doesn't leave the window, and fixes the context menu going out of the window when created near the right border of the window.
Note this PR was reopened because I accidentally made it from my master branch the first time

Fix menu jumping to top of screen and disappearing to the right

---

documentation/demo/menu-promise.md

* fixes right-click issue in async-create
* demos context menus for text input fields

Add demo for promise-based context menu in text input
